; Modified from ta_gcd/gcd_array.ll, which is generated by clang
; ModuleID = 'assign_hand.c'
source_filename = "assign_hand.c"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-pc-linux-gnu"

; Function Attrs: noinline nounwind optnone sspstrong uwtable
define dso_local i32 @main() #0 {
    ; actually I prefer ret i32 20 ......
    %1 = alloca [10 x i32], align 16
    %2 = getelementptr inbounds [10 x i32], [10 x i32]* %1, i64 0, i64 0
    store i32 10, i32* %2
    %3 = load i32, i32* %2
    %4 = mul i32 %3, 2
    %5 = getelementptr inbounds [10 x i32], [10 x i32]* %1, i64 0, i64 1
    store i32 %4, i32* %5
    %6 = load i32, i32* %5
    ret i32 %6
}

attributes #0 = { noinline nounwind optnone sspstrong uwtable "disable-tail-calls"="false" "frame-pointer"="all" "less-precise-fpmad"="false" "min-legal-vector-width"="0" "no-infs-fp-math"="false" "no-jump-tables"="false" "no-nans-fp-math"="false" "no-signed-zeros-fp-math"="false" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cx8,+fxsr,+mmx,+sse,+sse2,+x87" "tune-cpu"="generic" "unsafe-fp-math"="false" "use-soft-float"="false" }

!llvm.module.flags = !{!0, !1, !2}
!llvm.ident = !{!3}

!0 = !{i32 1, !"wchar_size", i32 4}
!1 = !{i32 7, !"PIC Level", i32 2}
!2 = !{i32 7, !"PIE Level", i32 2}
!3 = !{!"clang version 12.0.1"}
